### ISSUE TITLE
SVG is not resized properly on loading

### ISSUE THREAD

**Issue by andreyts** [ticketevolution/seatmaps-client#107]
Map wrapper has width=800 and height=600 attributes. As result there is no way to fit map in wrapper if wrapper has width more than 800px or height more than 600px.
It can be resolved if change these attributes or specify them in styles in pixels.
![screenshot-2019 03 01-20-08-05](https://user-images.githubusercontent.com/574326/53654121-fe71b280-3c5d-11e9-9a50-81fbbd45540a.png)

Also can "callback" be added on map loading?

**Comment by josephspens** [comment]
Hey @andreyts,

If you update your seatmaps version you should see the map no filling its container. As for the loading callback, that's an interesting feature and we'll consider it.

Joe
