### ISSUE TITLE
Hover tooltip is in wrong position in FF

### ISSUE THREAD

**Issue by andreyts** [ticketevolution/seatmaps-client#154]
Hover tooltip is in wrong position in FF 66.0.+.
There is no issue in Chrome.

**Comment by josephspens** [comment]
Thanks @andreyts! We'll look into this.

**Comment by Pharserror** [comment]
@andreyts will you post a screenshot of the problem with a link to the page you're seeing the problem on, please?

**Comment by andreyts** [comment]
attached


вт, 16 апр. 2019 г. в 18:45, Adam Lind <notifications@github.com>:

**Comment by andreyts** [comment]
http://tinypic.com/view.php?pic=2jejwh&s=9#.XLbVE9glFlZ
