### ISSUE TITLE
Map won't display

### ISSUE THREAD

**Issue by ElStone** [ticketevolution/seatmaps-client#168]
Trying to get a map to display using the window object, but all that shows is the map legend and zoom buttons.  Inspecting the code it appears at the script has built the map with supplied data, but nothing appears in the window.  Test page is located at http://nomason.pntsdev.com/seatmaps.html

**Comment by mayavera** [comment]
Thanks for raising this issue! It seems like the map (SVG file) for that venue configuration is malformed. We'll work on fixing the file and keep you updated via this thread.

**Comment by ElStone** [comment]
It doesn't seem to matter what event/map I use.  It never displays.

**Comment by azizgithub92** [comment]
Any news on this? It seems be blank, same issue as @ElStone

**Comment by jwcobb** [comment]
@azizgithub92 Does the element that should contain the map have a default height?
