### ISSUE TITLE
Map is not loading in Safari (macos, ios)

### ISSUE THREAD

**Issue by andreyts** [ticketevolution/seatmaps-client#173]
There is exception:
<img width="1407" alt="screenshot_2019-07-11_19 10 14" src="https://user-images.githubusercontent.com/574326/61067383-0e6d8000-a410-11e9-90a5-07db75174275.png">

**Comment by andreyts** [comment]
It relates to Intl lib that we use to resolve issue

**Comment by mayavera** [comment]
Hi @andreyts, thanks for opening this issue! Would you mind providing some more context to the issue your experiencing? Which version of iOS Safari are you using? Also, which library are you using to handle internationalization?

**Comment by mayavera** [comment]
@andreyts are you using the [`intl` npm package](https://www.npmjs.com/package/intl) to polyfill [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) support on Safari?
