### ISSUE TITLE
Unable to render map using TevoMap

### ISSUE THREAD

**Issue by gouravkumarshakya** [ticketevolution/seatmaps-client#175]

**Comment by gouravkumarshakya** [comment]
Unable to render the Ticket Evolution Map using its Tevo Maps API.
I am encountering the following problems:
Within the TicketGroups interface, data fetched for 'tevo_section_name' appears to be invalid. Please tell which attribute data of Ticket Group is accepted by the above member.
![error_in_console](https://user-images.githubusercontent.com/33033579/63592309-ebb5b600-c5ce-11e9-8cc2-339aaf5ed405.png)
I am using the following code to implement a map in Ticket Evolution Seat-Map API.
![download](https://user-images.githubusercontent.com/33033579/63592343-fff9b300-c5ce-11e9-9d0c-13b2223b29e9.png)
Any suggestions or demo will be appreciated.
Thanks.

**Comment by jwcobb** [comment]
This is expected behavior when a section provided has not been mapped to a canonical section name. You may contact `catalog at ticket evolution dot com` with details and request the map be reviewed and sections mapped.
