### ISSUE TITLE
Map is all grey, no colors appear

### ISSUE THREAD

**Issue by Cascade-Habib** [ticketevolution/seatmaps-client#176]
I am using below code to populate Tevo maps, maps are loading but these are all grey. no colors appear. and the maps are not interactive, no tool tip etc. please see it here
https://ticketbash.com/tickets/united-center/t1661578/nba-all-star-game-tickets.aspx

The tevo_section_name and retail_price in below example is a real data received from "/v9/ticket_groups" webservice. 

<script type="text/javascript">
var data = [
{ tevo_section_name:'UPPER LEVEL ENDS',retail_price:1296.00},
{ tevo_section_name:'UPPER LEVEL ENDS',retail_price:1350.00},
{ tevo_section_name:'UPPER LEVEL ENDS',retail_price:1350.00},
{ tevo_section_name:'UPPER LEVEL ENDS',retail_price:1350.00},
{ tevo_section_name:'UPPER LEVEL CORNERS',retail_price:1512.00},
{ tevo_section_name:'UPPER LEVEL CORNERS',retail_price:1620.00},
{ tevo_section_name:'UPPER LEVEL CORNERS',retail_price:1620.00},
{ tevo_section_name:'UPPER LEVEL CORNERS',retail_price:1620.00},
{ tevo_section_name:'UPPER LEVEL SIDELINES',retail_price:2106.00},
{ tevo_section_name:'UPPER LEVEL SIDES',retail_price:2430.00},
{ tevo_section_name:'UPPER LEVEL SIDES',retail_price:2430.00},
{ tevo_section_name:'UPPER LEVEL SIDES',retail_price:2430.00},
{ tevo_section_name:'LOWER ENDS & CORNERS',retail_price:3780.00},
{ tevo_section_name:'LOWER ENDS & CORNERS',retail_price:3780.00},
{ tevo_section_name:'LOWER ENDS & CORNERS',retail_price:3780.00},
{ tevo_section_name:'SILVER VIP',retail_price:3844.80},
{ tevo_section_name:'SILVER PREMIUM VIP',retail_price:4233.60},
{ tevo_section_name:'SILVER HOTEL',retail_price:4498.20},
{ tevo_section_name:'GOLD VIP',retail_price:7052.40},
{ tevo_section_name:'GOLD HOTEL',retail_price:7705.80},
{ tevo_section_name:'LOWER SIDES',retail_price:10260.00},
{ tevo_section_name:'LOWER SIDES',retail_price:10260.00},
{ tevo_section_name:'LOWER SIDES',retail_price:10260.00},
{ tevo_section_name:'GOLD PREMIUM VIP',retail_price:19234.80}
];
  
   var seatmap = new Tevomaps({
   venueId: '1633',
   configurationId: '5516'
   ,
   var seatmapApi = seatmap.build('my-map');
   seatmapApi.highlightSection('Madison Square Garden');
    
</script>

**Comment by mayavera** [comment]
Thanks for using this library and opening this ticket! Unfortunately, the section names from the ticket group listings don't correspond to the names of the map sections. This can happen from time to time and we are working hard to prevent this sort of mismatch. Thank you for your patience!

Have you noticed similar behavior for other events?
